apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - image: {{.Values.image}}
        name: {{.Values.name}}
        ports:
        - containerPort: {{.Values.serviceTargetPort}}
          name: service-port
